name: CI Pipeline

on: [push]

jobs:
  build_job:  # Ändere 'build' zu 'build_job' oder einem anderen Namen, falls gewünscht
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn -B dependency:resolve dependency:resolve-plugins

      - name: Run tests
        run: mvn test

      - name: Check test results
        run: |
          TEST_RESULTS=$(mvn surefire-report:report-only | grep -E 'Tests run: [0-9]+, Failures: [0-9]+, Errors: [0-9]+, Skipped: [0-9]+' | tail -1)
          echo "Test results: $TEST_RESULTS"
          TESTS_RUN=$(echo $TEST_RESULTS | grep -oP 'Tests run: \K[0-9]+')
          TESTS_FAILED=$(echo $TEST_RESULTS | grep -oP 'Failures: \K[0-9]+')
          TESTS_ERRORS=$(echo $TEST_RESULTS | grep -oP 'Errors: \K[0-9]+')
          TESTS_PASSED=$((TESTS_RUN - TESTS_FAILED - TESTS_ERRORS))
          PASS_RATE=$((100 * TESTS_PASSED / TESTS_RUN))
          echo "Pass rate: $PASS_RATE%"
          if [ $PASS_RATE -lt 80 ]; then
            echo "Less than 80% of tests passed. Failing the build."
            exit 1
