name: Java CI/CD

on:
  push:
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  # Build Job
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: mvn --batch-mode -DskipTests package

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: target/*.jar

  # Test Job
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: target

      - name: Run Tests
        run: mvn --batch-mode test

      - name: Analyze Test Results
        run: |
          TOTAL_TESTS=$(grep -oP '(?<=<testsuite[^>]*tests=")\d+' target/surefire-reports/*.xml | awk '{s+=$1} END {print s}')
          FAILED_TESTS=$(grep -oP '(?<=<testsuite[^>]*failures=")\d+' target/surefire-reports/*.xml | awk '{s+=$1} END {print s}')
          SUCCESSFUL_TESTS=$((TOTAL_TESTS - FAILED_TESTS))
          SUCCESS_RATE=$(echo "scale=2; ($SUCCESSFUL_TESTS / $TOTAL_TESTS) * 100" | bc)

          echo "Total Tests: $TOTAL_TESTS"
          echo "Failed Tests: $FAILED_TESTS"
          echo "Success Rate: $SUCCESS_RATE%"

          if (( $(echo "$SUCCESS_RATE < 75" | bc -l) )); then
            echo "❌ Test Success Rate is below 75%! ($SUCCESS_RATE%)"
            exit 1
          else
            echo "✅ Test Success Rate is acceptable. ($SUCCESS_RATE%)"
          fi

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
